/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedFacturesRouteImport } from './routes/_authenticated/factures'
import { Route as AuthenticatedDossiersIndexRouteImport } from './routes/_authenticated/dossiers.index'
import { Route as AuthenticatedDossiersNewRouteImport } from './routes/_authenticated/dossiers.new'
import { Route as AuthenticatedDossiersArchivesRouteImport } from './routes/_authenticated/dossiers.archives'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturesRoute = AuthenticatedFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersIndexRoute =
  AuthenticatedDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDossiersNewRoute =
  AuthenticatedDossiersNewRouteImport.update({
    id: '/dossiers/new',
    path: '/dossiers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDossiersArchivesRoute =
  AuthenticatedDossiersArchivesRouteImport.update({
    id: '/dossiers/archives',
    path: '/dossiers/archives',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/import': typeof AuthenticatedImportRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/dossiers/archives': typeof AuthenticatedDossiersArchivesRoute
  '/dossiers/new': typeof AuthenticatedDossiersNewRoute
  '/dossiers/': typeof AuthenticatedDossiersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/import': typeof AuthenticatedImportRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/': typeof AuthenticatedIndexRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/dossiers/archives': typeof AuthenticatedDossiersArchivesRoute
  '/dossiers/new': typeof AuthenticatedDossiersNewRoute
  '/dossiers': typeof AuthenticatedDossiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/factures': typeof AuthenticatedFacturesRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/_authenticated/dossiers/archives': typeof AuthenticatedDossiersArchivesRoute
  '/_authenticated/dossiers/new': typeof AuthenticatedDossiersNewRoute
  '/_authenticated/dossiers/': typeof AuthenticatedDossiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/factures'
    | '/import'
    | '/parametres'
    | '/dossiers/$id'
    | '/dossiers/archives'
    | '/dossiers/new'
    | '/dossiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/factures'
    | '/import'
    | '/parametres'
    | '/'
    | '/dossiers/$id'
    | '/dossiers/archives'
    | '/dossiers/new'
    | '/dossiers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/factures'
    | '/_authenticated/import'
    | '/_authenticated/parametres'
    | '/_authenticated/'
    | '/_authenticated/dossiers/$id'
    | '/_authenticated/dossiers/archives'
    | '/_authenticated/dossiers/new'
    | '/_authenticated/dossiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures': {
      id: '/_authenticated/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthenticatedFacturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/': {
      id: '/_authenticated/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers/'
      preLoaderRoute: typeof AuthenticatedDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/new': {
      id: '/_authenticated/dossiers/new'
      path: '/dossiers/new'
      fullPath: '/dossiers/new'
      preLoaderRoute: typeof AuthenticatedDossiersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/archives': {
      id: '/_authenticated/dossiers/archives'
      path: '/dossiers/archives'
      fullPath: '/dossiers/archives'
      preLoaderRoute: typeof AuthenticatedDossiersArchivesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFacturesRoute: typeof AuthenticatedFacturesRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRoute
  AuthenticatedDossiersArchivesRoute: typeof AuthenticatedDossiersArchivesRoute
  AuthenticatedDossiersNewRoute: typeof AuthenticatedDossiersNewRoute
  AuthenticatedDossiersIndexRoute: typeof AuthenticatedDossiersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFacturesRoute: AuthenticatedFacturesRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRoute,
  AuthenticatedDossiersArchivesRoute: AuthenticatedDossiersArchivesRoute,
  AuthenticatedDossiersNewRoute: AuthenticatedDossiersNewRoute,
  AuthenticatedDossiersIndexRoute: AuthenticatedDossiersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
